"use client";
import { useState } from "react";
import { ArrowLeft,X,Eye,EyeOff,LockKeyhole } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export function LoginModal({module,onClose}:{module:string;onClose:()=>void}){
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const router=useRouter();
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const destination=`/dashboard?module=${module}`;const supabase=createClient();if(!supabase){toast.info("Modo demostración: configura Supabase para habilitar autenticación real.");router.push(destination);return}const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)return toast.error(error.message);router.push(destination);router.refresh()}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-[#020914]/80 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-7 text-slate-900 shadow-2xl"><button type="button" onClick={onClose} className="mb-6 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-blue-700 hover:bg-blue-50"><ArrowLeft size={18}/>Volver a módulos</button><div className="flex items-start justify-between"><div><span className="label text-blue-700">Control de acceso</span><h2 className="mt-2 text-2xl font-black text-slate-950">Iniciar sesión</h2><p className="mt-1 text-sm text-slate-600 capitalize">Gestión {module}</p></div><button type="button" onClick={onClose} aria-label="Cerrar modal" className="rounded-xl p-2 text-slate-600 hover:bg-slate-100 hover:text-slate-950"><X/></button></div><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold text-slate-800">Correo electrónico<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="usuario@campana.co" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal text-slate-950 placeholder:text-slate-400"/></label><label className="block text-sm font-bold text-slate-800">Contraseña<div className="relative mt-2"><input required type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Ingrese su contraseña" className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 pr-12 font-normal text-slate-950 placeholder:text-slate-400"/><button type="button" onClick={()=>setShow(!show)} aria-label="Ver contraseña" className="absolute right-3 top-3 text-slate-500 hover:text-blue-700">{show?<EyeOff/>:<Eye/>}</button></div></label><p className="flex gap-2 rounded-xl bg-blue-50 p-3 text-xs text-blue-800"><LockKeyhole size={16}/>Acceso cifrado y permisos automáticos según el rol asignado.</p><button disabled={busy} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white hover:bg-blue-700 disabled:opacity-60">{busy?"Verificando…":"Ingresar al sistema"}</button></form></div></div>
}
