"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Crown, Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export default function OwnerLogin() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const router=useRouter();
  async function submit(event:React.FormEvent) { event.preventDefault(); setBusy(true); const supabase=createClient(); if(!supabase){setBusy(false);return toast.error("Supabase Auth no está configurado")}const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user){setBusy(false);return toast.error("Credenciales no válidas")}const {data:profile}=await supabase.from("profiles").select("role,status").eq("id",data.user.id).single();if(!profile||!["SUPERADMIN","GLOBAL_ADMIN"].includes(String(profile.role).toUpperCase())||!["ACTIVE","ACTIVO"].includes(String(profile.status).toUpperCase())){await supabase.auth.signOut();setBusy(false);return toast.error("La cuenta no tiene acceso de propietario global")}router.push("/global-admin/panel");router.refresh() }
  return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-[#06111f] p-5 text-white"><div className="absolute inset-0 opacity-70 [background-image:radial-gradient(circle_at_70%_20%,rgba(37,99,235,.35),transparent_32%),radial-gradient(circle_at_20%_80%,rgba(245,158,11,.1),transparent_26%)]"/><div className="absolute inset-0 opacity-[.04] [background-image:linear-gradient(#fff_1px,transparent_1px),linear-gradient(90deg,#fff_1px,transparent_1px)] [background-size:64px_64px]"/><section className="relative w-full max-w-md rounded-[28px] border border-white/10 bg-white/[.07] p-2 shadow-2xl backdrop-blur-xl"><div className="rounded-[22px] bg-white p-7 text-slate-900"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-blue-600"><ArrowLeft size={17}/>Volver al portal</Link><div className="mt-7 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-amber-100 text-amber-600"><Crown size={28}/></span><div><p className="label text-amber-600">Área privada</p><h1 className="mt-1 text-2xl font-black">Acceso del propietario</h1></div></div><p className="mt-5 text-sm leading-6 text-slate-500">Panel exclusivo para la administración global de Campaña Ganadora AI.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold">Correo del propietario<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal text-slate-950"/></label><label className="block text-sm font-bold">Contraseña<div className="relative mt-2"><input required type={show?"text":"password"} value={password} onChange={event=>setPassword(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 pr-12 font-normal text-slate-950"/><button type="button" onClick={()=>setShow(!show)} aria-label="Mostrar contraseña" className="absolute right-3 top-3 text-slate-400">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="flex gap-3 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><ShieldCheck className="shrink-0 text-emerald-600" size={18}/><span>Ruta privada con verificación de sesión y rol global de propietario.</span></div><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#071326] py-3.5 font-black text-white hover:bg-blue-700 disabled:opacity-60"><LockKeyhole size={18}/>{busy?"Verificando…":"Ingresar al control global"}</button></form></div></section></main>;
}
